name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: jco-digital/deploy-wp-action/.github/workflows/build-project.yml@v3.3.1
    with:
      php_version: 8.2
      slack_channel: C07C91377D4
    secrets: inherit
  deploy:
    needs: [build]
    uses: jco-digital/deploy-wp-action/.github/workflows/server-deploy.yml@v3.3.1
    with:
      server_url: rekai@vi.bojaco.com
      base_path: files
      paths: >-
        wp-content/plugins/:wp-content/plugins/,
      slack_channel: C07C91377D4
    secrets: inherit
